/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import auxiliar.Pair;
import db.DB;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.dao.FornecedoraDao;
import model.dao.TransportadoraDao;
import model.dao.implementations.FornecedoraDaoJDBC;
import model.dao.implementations.TransportadoraDaoJDBC;
import model.entities.Transportadora;


/**
 *
 * @author silvi
 */
public class TransportadoraView extends javax.swing.JFrame {

private static TransportadoraView transpUnic;

    private TransportadoraView() throws ClassNotFoundException {
        initComponents();
        preencherTabela();
    }

    public static TransportadoraView getTransp() throws ClassNotFoundException {
        if (transpUnic == null) {
            transpUnic = new TransportadoraView();
        }
        return transpUnic;
    }

    public void mostrar() {
        this.setVisible(true);
        try {
            preencherTabela();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TransportadoraView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ocultar() {
        this.setVisible(false);
    try {
        preencherTabela();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(TransportadoraView.class.getName()).log(Level.SEVERE, null, ex);
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCnpj = new javax.swing.JLabel();
        jTextFieldCnpj = new javax.swing.JTextField();
        jLabelRazaoSocial = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelLogradouro = new javax.swing.JLabel();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTransportadora = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transportadora");
        setPreferredSize(new java.awt.Dimension(1600, 900));
        setSize(new java.awt.Dimension(1600, 900));

        jLabelCnpj.setText("CNPJ :");

        jLabelRazaoSocial.setText("Razão Social : ");

        jTextFieldRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRazaoSocialActionPerformed(evt);
            }
        });

        jLabelEmail.setText("E-mail : ");

        jLabelTelefone.setText("Telefone : ");

        jLabelLogradouro.setText("Logradouro : ");

        jLabelNumero.setText("Número :");

        jLabelCep.setText("CEP : ");

        jLabelCidade.setText("Cidade : ");

        jLabelEstado.setText("Estado :");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        tabelaTransportadora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CNPJ", "Razão Social", "Email", "Telefone", "Logradouro", "Numero", "CEP", "Cidade", "Estado", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTransportadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTransportadoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaTransportadora);
        if (tabelaTransportadora.getColumnModel().getColumnCount() > 0) {
            tabelaTransportadora.getColumnModel().getColumn(0).setMinWidth(40);
            tabelaTransportadora.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelaTransportadora.getColumnModel().getColumn(0).setMaxWidth(40);
            tabelaTransportadora.getColumnModel().getColumn(6).setPreferredWidth(70);
            tabelaTransportadora.getColumnModel().getColumn(6).setMaxWidth(70);
            tabelaTransportadora.getColumnModel().getColumn(9).setMaxWidth(40);
            tabelaTransportadora.getColumnModel().getColumn(10).setMaxWidth(40);
            tabelaTransportadora.getColumnModel().getColumn(11).setMaxWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCnpj)
                                .addGap(47, 47, 47)
                                .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRazaoSocial)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEmail)
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTelefone)
                                .addGap(32, 32, 32)
                                .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLogradouro)
                                    .addComponent(jLabelCep))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNumero)
                                    .addComponent(jLabelCidade))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                        .addGap(874, 989, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEstado)
                                .addGap(42, 42, 42)
                                .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastrar)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCnpj)
                            .addComponent(jLabelRazaoSocial))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelTelefone))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogradouro)
                                .addGap(12, 12, 12)
                                .addComponent(jLabelCep))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNumero)
                                .addGap(12, 12, 12)
                                .addComponent(jLabelCidade)))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEstado)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadastrar)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRazaoSocialActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

          cadastrarTransportadora();
    }//GEN-LAST:event_btnCadastrarActionPerformed


    private void tabelaTransportadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTransportadoraMouseClicked
        try {
            int row = tabelaTransportadora.rowAtPoint(evt.getPoint());
            int col = tabelaTransportadora.columnAtPoint(evt.getPoint());
            Transportadora transportadora = new Transportadora();
            TransportadoraDao transportadoraDao = new TransportadoraDaoJDBC(DB.getConnection());
            if (col == tabelaTransportadora.getColumnCount() - 2) {
                int traId = (int) tabelaTransportadora.getValueAt(row, 0);
                System.out.print(traId);
                transportadora.setTraId(traId);
                transportadoraDao.deleteById(transportadora);

            } else if (col == tabelaTransportadora.getColumnCount() - 1) {
                editarTransportadora();
            }
            preencherTabela();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TransportadoraView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaTransportadoraMouseClicked

    private void preencherTabela() throws ClassNotFoundException {
        TransportadoraDao transportadoraDao = new TransportadoraDaoJDBC(DB.getConnection());
        List<Transportadora> transportadoras = transportadoraDao.findAll();

        DefaultTableModel model = (DefaultTableModel) tabelaTransportadora.getModel();
        model.setRowCount(0);
        
        for (Transportadora transportadora : transportadoras) {
            Object[] row = {
                transportadora.getTraId(),
                transportadora.getTraCnpj(),
                transportadora.getTraRazaoSocial(),
                transportadora.getTraEmail(),
                transportadora.getTraTelefone(),
                transportadora.getTraLogradouro(),
                transportadora.getTraNumero(),
                transportadora.getTraCep(),
                transportadora.getTraCidade(),
                transportadora.getTraEstado(),
                "Alterar",
                "Excluir"
            };
            model.addRow(row);
        }
    }
    

    private void cadastrarTransportadora() {
        try {
            String cnpj = jTextFieldCnpj.getText();
            String razaoSocial = jTextFieldRazaoSocial.getText();
            String email = jTextFieldEmail.getText();
            String telefone = jTextFieldTelefone.getText();
            String logradouro = jTextFieldLogradouro.getText();
            int numero = Integer.parseInt(jTextFieldNumero.getText());
            int cep = Integer.parseInt(jTextFieldCep.getText());
            String cidade = jTextFieldCidade.getText();
            String estado = jTextFieldEstado.getText();

            Transportadora novaTransportadora = new Transportadora();
            novaTransportadora.setTraCnpj(cnpj);
            novaTransportadora.setTraRazaoSocial(razaoSocial);
            novaTransportadora.setTraEmail(email);
            novaTransportadora.setTraTelefone(telefone);
            novaTransportadora.setTraLogradouro(logradouro);
            novaTransportadora.setTraNumero(numero);
            novaTransportadora.setTraCep(cep);
            novaTransportadora.setTraCidade(cidade);
            novaTransportadora.setTraEstado(estado);

            TransportadoraDao transportadoraDao = new TransportadoraDaoJDBC(DB.getConnection());
            transportadoraDao.insert(novaTransportadora);
            limparCampos();
            preencherTabela();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Número inválido. Certifique-se de fornecer valores numéricos para campos como Número e CEP.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar a transportadora: " + ex.getMessage());
        }
    }

    private void limparCampos() {
        jTextFieldCnpj.setText("");
        jTextFieldRazaoSocial.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldLogradouro.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCep.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
    }
    
    private void editarTransportadora() {
    try {
        int selectedRow = tabelaTransportadora.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma transportadora para editar.");
            return;
        }
        int traId = (int) tabelaTransportadora.getValueAt(selectedRow, 0);
        TransportadoraDao transportadoraDao = new TransportadoraDaoJDBC(DB.getConnection());
        
        Transportadora transportadoraExistente = new Transportadora();
        transportadoraExistente.setTraId(traId);
        transportadoraExistente = transportadoraDao.findById(transportadoraExistente);
        Transportadora novaTransportadora = new Transportadora();

        JTextField txtCnpj = new JTextField(transportadoraExistente.getTraCnpj());
        JTextField txtRazaoSocial = new JTextField(transportadoraExistente.getTraRazaoSocial());
        JTextField txtEmail = new JTextField(transportadoraExistente.getTraEmail());
        JTextField txtTelefone = new JTextField(transportadoraExistente.getTraTelefone());
        JTextField txtLogradouro = new JTextField(transportadoraExistente.getTraLogradouro());
        JTextField txtNumero = new JTextField(String.valueOf(transportadoraExistente.getTraNumero()));
        JTextField txtCep = new JTextField(String.valueOf(transportadoraExistente.getTraCep()));
        JTextField txtCidade = new JTextField(transportadoraExistente.getTraCidade());
        JTextField txtEstado = new JTextField(transportadoraExistente.getTraEstado());

        // Crie um array de objetos com os campos de texto
        Object[] fields = {
            "CNPJ:", txtCnpj,
            "Razão Social:", txtRazaoSocial,
            "Email:", txtEmail,
            "Telefone:", txtTelefone,
            "Logradouro:", txtLogradouro,
            "Número:", txtNumero,
            "CEP:", txtCep,
            "Cidade:", txtCidade,
            "Estado:", txtEstado
        };

        // Exiba o popup para editar
        int result = JOptionPane.showConfirmDialog(this, fields, "Editar Transportadora", JOptionPane.OK_CANCEL_OPTION);

        // Se o usuário pressionar OK, atualize a transportadora
        if (result == JOptionPane.OK_OPTION) {
            novaTransportadora.setTraId(traId);
            novaTransportadora.setTraCnpj(txtCnpj.getText());
            novaTransportadora.setTraRazaoSocial(txtRazaoSocial.getText());
            novaTransportadora.setTraEmail(txtEmail.getText());
            novaTransportadora.setTraTelefone(txtTelefone.getText());
            novaTransportadora.setTraLogradouro(txtLogradouro.getText());
            novaTransportadora.setTraNumero(Integer.parseInt(txtNumero.getText()));
            novaTransportadora.setTraCep(Integer.parseInt(txtCep.getText()));
            novaTransportadora.setTraCidade(txtCidade.getText());
            novaTransportadora.setTraEstado(txtEstado.getText());

            // Atualize a transportadora no banco de dados
            transportadoraDao.update(novaTransportadora);

            // Atualize a tabela após a edição
            preencherTabela();
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Número inválido. Certifique-se de fornecer valores numéricos para campos como Número e CEP.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erro ao editar a transportadora: " + ex.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCnpj;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRazaoSocial;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCnpj;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTable tabelaTransportadora;
    // End of variables declaration//GEN-END:variables
}
